# Generated by Django 4.2.1 on 2023-06-03 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3aa76108-0ce3-4ee6-9668-4ef960593821')),
        ),
    ]
