# Generated by Django 4.2.1 on 2023-06-04 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_alter_chatbot_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("dd5f5798-50b5-4da9-bce5-b9fc54005daa")
            ),
        ),
    ]
